
MAKE=make
CC=g++ -frtti -fPIC --std=c++11
LD=g++ -frtti -fPIC
RM=rm
AR=ar
PARAM=-fpermissive -c -DLinux

VERSION=0.0.1
THREAD=1
SRC_PATH=.
LIB_PATH=lib
OUT_PATH=../bin
DEBUG=0
NEED_BOOST=1

CC_FLAG=-I../pj/include -I./  -I../include -I../include/mqtt -I../include/jrtplib3

LD_FLAG = -L../pj/lib -L../lib -L../boost/lib -lpthread -lc -lrt -lm
PJ_SHARED_LIBS= -lpjlib-util -lpjmedia-codec -lpjmedia -lpjnath -lpjsip -lpjsip-ua -lpj -lpjsua -lsrtp -lspeex  -lresample -lyuv -lgsmcodec -lilbccodec -lg7221codec -lpjsip-simple -lpjmedia-audiodev -lpjmedia-videodev
STATIC_LIBS = ../lib/libmosquitto.a ../lib/libjsoncpp.a ../lib/libjrtp.a ../lib/libpthread_nonshared.a ../lib/libc_nonshared.a ../lib/libtcmalloc.a

PJ_STATIC_LIBS= \
	../pj/lib/libpj-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjlib-util-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjnath-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjsip-ua-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjsua-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjsua2-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjmedia-codec-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjmedia-x86_64-unknown-linux-gnu.a \
	../pj/lib/libsrtp-x86_64-unknown-linux-gnu.a \
	../pj/lib/libresample-x86_64-unknown-linux-gnu.a \
	../pj/lib/libyuv-x86_64-unknown-linux-gnu.a \
	../pj/lib/libilbccodec-x86_64-unknown-linux-gnu.a \
	../pj/lib/libg7221codec-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjsip-simple-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjmedia-audiodev-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjmedia-videodev-x86_64-unknown-linux-gnu.a  \
	../pj/lib/libspeex-x86_64-unknown-linux-gnu.a \
	../pj/lib/libpjsip-x86_64-unknown-linux-gnu.a
	
ifneq ($(NEED_BOOST), 0)
    PARAM += -DNEED_BOOST -D_SCL_SECURE_NO_WARNINGS
    CC_FLAG += -I../boost/include
    STATIC_LIBS += ../boost/lib/libboost_regex.a
endif	
